#!/bin/bash
#-----------------------------------------------------------------------------
declare dtu_base=$(
  _program="$0"
  case "$_program" in
    (*/*) ;;
    (*) _program=$(command -v -- "$0")
  esac
  [[ -L "$_program" ]] && _program=$(readlink "$_program")
  cd -P -- "$(dirname -- "$_program")" && pwd -P
)

declare dtu_updaters_path="$dtu_base/updaters"
#-----------------------------------------------------------------------------
if [[ ! -d "$dtu_updaters_path" ]] ; then
  echo "$0 could not find '$dtu_updaters_path'"
  exit 1
fi
#-----------------------------------------------------------------------------
declare -a updaters=$(find -s "$dtu_updaters_path" -type f -name '*.sh')
#-----------------------------------------------------------------------------
[[ $# -gt 0 ]] || usage
#-----------------------------------------------------------------------------
parse_config() {
  local _file="$1"
  local _only="$2"
  [[ -n "$_only" ]] || return
  [[ -s "$_file" ]] || return

  local _pretty
  local _blank='^\s*$'
  local _comment='^\s*#'

  local -a _config

  while read -r _line ; do
    [[ "$_line" =~ $_blank ]] && continue
    [[ "$_line" =~ $_comment ]] && continue

    if [[ "$_line" =~ ^[[:space:]]*([^[:space:]]+)[[:space:]]*:.*$ ]] ; then
      _pretty="${BASH_REMATCH[1]}"
    elif [[ "$_line" =~ ^[[:space:]]*([^#[:space:]]+)[[:space:]]*.*$ ]] ; then
      [[ "$_only" == "$_pretty" ]] && _config+=(${BASH_REMATCH[1]})
    fi
  done < "$_file"

  echo "${_config[@]}"
}
#-----------------------------------------------------------------------------
usage() {
  cat <<USAGE
Usage: ${0##*/} [options] <command> [command...]
  OPTIONS:
  -h, --help      This.
  -q, --quiet     Run each updater with no output.
  -t, --terse     Run each updater with terse, ok/error style output.
  -v, --verbose   Run each updater with their natural output level.

  COMMANDS:
  all             Run all the updaters.
USAGE

  for _script in ${updaters[@]} ; do
    echo -n '  '
    pretty "$_script"
  done

  exit 1
}
#-----------------------------------------------------------------------------
broken() {
  local _script="$1"

  echo "$_script doesn't appear to define an 'updater' function"
  exit 1
}
#-----------------------------------------------------------------------------
pretty() {
  local _script="$1"
  local _name=$(basename "$_script")
  [[ "${_name:2:1}" == '_' ]] && _name="${_name:3}"
  echo "${_name%%.sh}"
}
#-----------------------------------------------------------------------------
run_one() {
  local _script="$1"
  local _output_style="$2"
  local _pretty=$(pretty "$_script")

  if [[ ! -s "$_script" ]] ; then
    echo "$_script is missing or empty."
    exit 1
  fi

  unset -f updater
  local -a tools=($(parse_config "$HOME/.dtu" "$_pretty"))
  source "$_script"
  declare -f updater >&/dev/null || broken "$_script"

  case "$_output_style" in
    terse)
      _tmp=$(mktemp)
      echo -ne "$_pretty \t>>\t"

      if updater "$_script" >&"$_tmp" ; then
        echo 'ok'
      else
        echo 'err'
        [[ -s "$_tmp" ]] && cat "$_tmp"
      fi

      rm "$_tmp"
      ;;
    quiet)
      updater >& /dev/null
      ;;
    *)
      echo "Running updater $_pretty ($_script)"
      updater
      ;;
  esac
}
#-----------------------------------------------------------------------------
run_all() {
  local _output_style="$1"
  for _script in ${updaters[@]} ; do
    run_one "$_script" "$_output_style"
  done
}
#-----------------------------------------------------------------------------
declare _output_style

for _command in "$@" ; do
  case "$_command" in
    -h|help) usage ;;
    -t|--terse) _output_style='terse' ;;
    -q|--quiet) _output_style='quiet' ;;
    -v|--verbose) _output_style='verbose' ;;
    all) run_all ${_output_style:terse} ;;
    *) run_one "$dtu_updaters_path/"??"_${_command}.sh" ${_output_style} ;;
  esac
done
#-----------------------------------------------------------------------------
